### ISSUE TITLE
Validate birthday to ensure that user will be an adult during the event

### ISSUE THREAD

**Issue by lindsaln** [mihi-r/ceas-tribunal-luau-tickets#27]
A student must be at least 18 to attend this event. This is due to insurance complications with being a minor. This check should be done on the php side and pull the date of the event from the luau_tickets_info table.

**Comment by lindsaln** [comment]
What info is in the luau_tickets_info table? Is event date one of the field options?

**Comment by mihi-r** [comment]
Check out the luau_tickets_info.sql in the schema directory to see what's in that table. Would you like to add an event date? Or would you just like to check their age with the current date?

**Comment by lindsaln** [comment]
> Check out the luau_tickets_info.sql in the schema directory to see what's in that table. Would you like to add an event date? Or would you just like to check their age with the current date?

We can check with the current date. My thought was that there might be someone who turns 18 between when they register versus the date of the event, but that would probably happen to 1 person.

**Comment by mihi-r** [comment]
Hmmm, we should probably still handle that edge case then. I can add an additional attribute in the schema for the event to allow us to check if the user is the correct age.
