### ISSUE TITLE
Email is displaying "\n" characters when sent to the user

### ISSUE THREAD

**Issue by mihi-r** [mihi-r/ceas-tribunal-luau-tickets#30]
It seems like the email is explicitly showing the newline characters in the email. We will have to figure out how to fix that for PHPMailer.

**Comment by lindsaln** [comment]
I looked into a couple articles and this is what I found: https://stackoverflow.com/questions/22839027/phpmailer-ignoring-r-n

The suggestion was made to use double quotes instead of single quotes in this message. In sennd_reservation.php line 137, we currently have single quotes.

**Comment by lindsaln** [comment]
Or use this to alter the message: $message = str_replace(array('\r', '\n'), array(chr(10), chr(13)), $row['message']);

In the above example the person was using \r\n instead of just \n

**Comment by mihi-r** [comment]
@lindsaln Hmm, I will try this solution!
