### ISSUE TITLE
Change Super_Email in database to tribunal email

### ISSUE THREAD

**Issue by lindsaln** [mihi-r/ceas-tribunal-luau-tickets#40]
Hey Mihir, so I actually got access of the tribunal Gmail when I became president. So we can use this one now for stuff like this instead of having everything coming from the career fair email:

uc.eas.tribunal@gmail.com

I think we have a uc specific one for tribunal (tribunal@mail.uc.edu?) or something like that, but I don't know it off the top of my head. I'll look into it though.

Ahsan was pretty confused what the "ticket reservation" was because it came from careerfair@uc.edu, so I want to avoid this confusion in future situations.

**Comment by mihi-r** [comment]
@lindsaln yup, we can change the email pretty easily in the database. This doesn't have to do with the application on hand (it's not coded into our software) so I'll go ahead and close this issue.
